#!/bin/bash

# If you don't know what this file is, don't touch it.
# use this installer if you have problems with Makefile

INSTALLATION/install_dependencies.sh
INSTALLATION/build.sh

mkdir -p ~/MIDTF
sudo mv ~/MIDTF /usr/share

sudo cp -r build/libs/*.jar /usr/share/MIDTF
sudo cp -r INSTALLATION/midtf /usr/bin/
sudo cp -r INSTALLATION/midtf.1 /usr/share/man/man1/

sudo gzip /usr/share/man/man1/midtf.1

sudo chmod +x /usr/bin/midtf
sudo chmod +x /usr/share/MIDTF/*.jar