.TH midtf

.SH NAME
midtf \- A command-line tool showing detailed operating system information

.SH SYNOPSIS
.B midtf [\fIOPTION\fR] [\fIARG\fR]

.SH DESCRIPTION
midtf is a command line tool written in the Kotlin programming language. The tool will allow you to find out the necessary information about the operating system, components and even the name of the mouse cursor.

.SH OPTIONS
.TP
\fB\-h, \-\-help\fR
Displays a help message and exit.

.TP
\fB\-rm, \-\-uninstall\fR
self-destruction.

.TP
\fB\-d, \-\-detail\fR
Shows information only about the specified part and exit.

.SH COPYRIGHT
2024, Nikita Midvetb